CREATE TABLE otus."product" (
                           "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                           "name" varchar(50) NOT NULL,
                           "manufacturer_id" smallint NOT NULL
);

CREATE TABLE otus."product_category" (
                                    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                    "name" varchar(60) NOT NULL
);

CREATE TABLE otus."manufacturer" (
                                "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                "name" varchar(40) NOT NULL
);

CREATE TABLE otus."supplier" (
                            "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                            "name" varchar(40) NOT NULL
);

CREATE TABLE otus."purchase" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                            "customer_id" integer NOT NULL,
                            "purchase_delivary_date" date NOT NULL
);

CREATE TABLE otus."purchase_item" (
                                 "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                 "id_purchase" bigint NOT NULL,
                                 "id_product" integer NOT NULL,
                                 "id_supplier" integer NOT NULL,
                                 "product_count" integer NOT NULL,
                                 "sum" integer NOT NULL,
                                 "purchase_item_delivery_date" date NOT NULL
);

CREATE TABLE otus."customer" (
                            "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                            "email" varchar(30) NOT NULL,
                            "phone" varchar(10) NOT NULL
);

CREATE TABLE otus."product_item" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                "supplier_id" integer NOT NULL,
                                "product_id" integer NOT NULL,
                                "delivery_date" date NOT NULL,
                                "price" integer NOT NULL,
                                "count" integer NOT NULL
);

CREATE TABLE otus."credit_card" (
                               "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                               "card_number" varchar(20) NOT NULL,
                               "balance" integer NOT NULL,
                               "customer_id" integer NOT NULL
);

CREATE TABLE otus."product_category_ref" (
                                        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                        "product_category_id" smallint NOT NULL,
                                        "product_id" integer NOT NULL
);

COMMENT ON COLUMN otus."product"."name" IS 'Product name';

COMMENT ON COLUMN otus."product_category"."name" IS 'Product category name';

COMMENT ON COLUMN otus."manufacturer"."name" IS 'Manufacturer name';

COMMENT ON COLUMN otus."purchase"."purchase_delivary_date" IS 'Date of delivering the whole order';

COMMENT ON COLUMN otus."purchase_item"."product_count" IS 'Count of bought product';

COMMENT ON COLUMN otus."purchase_item"."sum" IS 'Total cost for current price and count';

COMMENT ON COLUMN otus."purchase_item"."purchase_item_delivery_date" IS 'Date of delivering the purchase';

COMMENT ON COLUMN otus."product_item"."delivery_date" IS 'Date when product can be delivered';

COMMENT ON COLUMN otus."product_item"."price" IS 'Price in minor unit';

COMMENT ON COLUMN otus."product_item"."count" IS 'Available count in warehousefor supplier';

COMMENT ON COLUMN otus."credit_card"."card_number" IS 'Credit card number';

COMMENT ON COLUMN otus."credit_card"."balance" IS 'Balance in minor unit';

ALTER TABLE otus."product" ADD FOREIGN KEY ("manufacturer_id") REFERENCES otus."manufacturer" ("id");

ALTER TABLE otus."purchase_item" ADD FOREIGN KEY ("id_purchase") REFERENCES otus."purchase" ("id");

ALTER TABLE otus."purchase_item" ADD FOREIGN KEY ("id_supplier") REFERENCES otus."supplier" ("id");

ALTER TABLE otus."purchase_item" ADD FOREIGN KEY ("id_product") REFERENCES otus."product" ("id");

ALTER TABLE otus."purchase" ADD FOREIGN KEY ("customer_id") REFERENCES otus."customer" ("id");

ALTER TABLE otus."credit_card" ADD FOREIGN KEY ("customer_id") REFERENCES otus."customer" ("id");

ALTER TABLE otus."product_item" ADD FOREIGN KEY ("supplier_id") REFERENCES otus."supplier" ("id");

ALTER TABLE otus."product_item" ADD FOREIGN KEY ("product_id") REFERENCES otus."product" ("id");

ALTER TABLE otus."product_category_ref" ADD FOREIGN KEY ("product_id") REFERENCES otus."product" ("id");

ALTER TABLE otus."product_category_ref" ADD FOREIGN KEY ("product_category_id") REFERENCES otus."product_category" ("id");