CREATE TABLE "product" (
                           "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                           "name" varchar(50) UNIQUE NOT NULL,
                           "manufacturer_fk" integer NOT NULL,
                           "unit_fk" integer UNIQUE NOT NULL
);

CREATE TABLE "unit" (
                        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                        "name" varchar(30) NOT NULL
);

CREATE TABLE "product_category" (
                                    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                    "name" varchar(60) UNIQUE NOT NULL
);

CREATE TABLE "manufacturer" (
                                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                "name" varchar(40) UNIQUE NOT NULL
);

CREATE TABLE "supplier" (
                            "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                            "name" varchar(40) UNIQUE NOT NULL
);

CREATE TABLE "purchase" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                            "customer_fk" integer NOT NULL,
                            "delivary_date" date NOT NULL
);

CREATE TABLE "purchase_item" (
                                 "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                 "purchase_fk" bigint NOT NULL,
                                 "product_item_fk" bigint NOT NULL,
                                 "amount" decimal(10,2) NOT NULL,
                                 "total_cost" decimal(10,2) NOT NULL,
                                 "delivery_date" date NOT NULL
);

CREATE TABLE "customer" (
                            "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                            "first_name" varchar(30) NOT NULL,
                            "last_name" varchar(30) NOT NULL
);

CREATE TABLE "email" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                         "email_text" varchar(30) UNIQUE NOT NULL,
                         "active" boolean NOT NULL DEFAULT true,
                         "main" boolean NOT NULL DEFAULT false,
                         "customer_fk" integer NOT NULL
);

CREATE TABLE "phone" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                         "phone_number" varchar(10) UNIQUE NOT NULL,
                         "active" boolean NOT NULL DEFAULT true,
                         "main" boolean NOT NULL DEFAULT false,
                         "customer_fk" integer NOT NULL
);

CREATE TABLE "product_item" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                "supplier_fk" integer NOT NULL,
                                "product_fk" integer NOT NULL,
                                "delivery_date" date NOT NULL,
                                "price" decimal(10,2) NOT NULL,
                                "amount" decimal(10,2) NOT NULL
);

CREATE TABLE "credit_card" (
                               "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                               "card_number" varchar(20) NOT NULL,
                               "balance" decimal(10,2) NOT NULL,
                               "customer_fk" integer NOT NULL,
                               "main" boolean NOT NULL DEFAULT false,
                               "active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "product_category_ref" (
                                        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                        "product_category_fk" integer NOT NULL,
                                        "product_fk" integer NOT NULL
);

COMMENT ON COLUMN "product"."name" IS 'Product name';

COMMENT ON COLUMN "product"."unit_fk" IS 'Product unit';

COMMENT ON COLUMN "unit"."name" IS 'Product unit';

COMMENT ON COLUMN "product_category"."name" IS 'Product category name';

COMMENT ON COLUMN "manufacturer"."name" IS 'Manufacturer name';

COMMENT ON COLUMN "purchase"."delivary_date" IS 'Date of delivering the whole order';

COMMENT ON COLUMN "purchase_item"."amount" IS 'Count of bought product';

COMMENT ON COLUMN "purchase_item"."total_cost" IS 'Total cost for current price and count';

COMMENT ON COLUMN "purchase_item"."delivery_date" IS 'Date of delivering the purchase';

COMMENT ON COLUMN "product_item"."delivery_date" IS 'Date when product can be delivered';

COMMENT ON COLUMN "product_item"."price" IS 'Price in minor unit';

COMMENT ON COLUMN "product_item"."amount" IS 'Available count in warehousefor supplier';

COMMENT ON COLUMN "credit_card"."card_number" IS 'Credit card number';

COMMENT ON COLUMN "credit_card"."balance" IS 'Balance in minor unit';

ALTER TABLE "product" ADD FOREIGN KEY ("unit_fk") REFERENCES "unit" ("id");

ALTER TABLE "product" ADD FOREIGN KEY ("manufacturer_fk") REFERENCES "manufacturer" ("id");

ALTER TABLE "purchase_item" ADD FOREIGN KEY ("purchase_fk") REFERENCES "purchase" ("id");

ALTER TABLE "purchase_item" ADD FOREIGN KEY ("product_item_fk") REFERENCES "product_item" ("id");

ALTER TABLE "purchase" ADD FOREIGN KEY ("customer_fk") REFERENCES "customer" ("id");

ALTER TABLE "credit_card" ADD FOREIGN KEY ("customer_fk") REFERENCES "customer" ("id");

ALTER TABLE "product_item" ADD FOREIGN KEY ("supplier_fk") REFERENCES "supplier" ("id");

ALTER TABLE "product_item" ADD FOREIGN KEY ("product_fk") REFERENCES "product" ("id");

ALTER TABLE "product_category_ref" ADD FOREIGN KEY ("product_fk") REFERENCES "product" ("id");

ALTER TABLE "product_category_ref" ADD FOREIGN KEY ("product_category_fk") REFERENCES "product_category" ("id");

ALTER TABLE "email" ADD FOREIGN KEY ("customer_fk") REFERENCES "customer" ("id");

ALTER TABLE "phone" ADD FOREIGN KEY ("customer_fk") REFERENCES "customer" ("id");