CREATE TABLESPACE ssdOrder LOCATION '/ssdOrder';
CREATE TABLESPACE hddOrder LOCATION '/hddOrder';

CREATE SCHEMA IF NOT EXISTS otus;

CREATE TABLE otus."customer" (
                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                 "first_name" varchar(30) NOT NULL,
                                 "last_name" varchar(30) NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."customer_history" (
                                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                         "history" json NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."email" (
                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                              "email_text" varchar(30) NOT NULL,
                              "active" boolean NOT NULL DEFAULT true,
                              "main" boolean NOT NULL DEFAULT false,
                              "customer_fk" int NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."manufacturer" (
                                     "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     "name" varchar(40) NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."phone" (
                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                              "phone_number" varchar(20) NOT NULL,
                              "active" boolean NOT NULL DEFAULT true,
                              "main" boolean NOT NULL DEFAULT false,
                              "customer_fk" int NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."product" (
                                "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                "name" varchar(50) NOT NULL,
                                "manufacturer_fk" int NOT NULL,
                                "unit_fk" int NOT NULL,
                                "description" text,
                                "product_search" tsvector
) TABLESPACE ssdOrder;

CREATE TABLE otus."product_category" (
                                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                         "name" varchar(60) NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."product_category_ref" (
                                             "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                             "product_category_fk" int NOT NULL,
                                             "product_fk" int NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."product_item" (
                                     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     "supplier_fk" int NOT NULL,
                                     "product_fk" int NOT NULL,
                                     "price" decimal(19,4) NOT NULL,
                                     "amount" decimal(10,2) NOT NULL,
                                     "warehouse_fk" int NOT NULL,
                                     "discount_percent" decimal(19,4) NOT NULL DEFAULT 0
) TABLESPACE ssdOrder;

CREATE TABLE otus."order" (
                              "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              "customer_id" int NOT NULL,
                              "delivary_date" date NOT NULL,
                              PRIMARY KEY ("id", "delivary_date")
) PARTITION BY RANGE (delivary_date);

CREATE TABLE otus.order_2024 PARTITION OF otus.order FOR VALUES FROM ('2024-01-01') TO ('2025-01-01') TABLESPACE ssdOrder ;
CREATE TABLE otus.order_2025 PARTITION OF otus.order FOR VALUES FROM ('2025-01-01') TO ('2026-01-01') TABLESPACE ssdOrder ;
CREATE TABLE otus.order_2026 PARTITION OF otus.order FOR VALUES FROM ('2026-01-01') TO ('2027-01-01') TABLESPACE ssdOrder ;
CREATE TABLE otus.order_2027 PARTITION OF otus.order FOR VALUES FROM ('2027-01-01') TO ('2028-01-01') TABLESPACE ssdOrder ;

CREATE TABLE otus."order_archive" (
                                      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                      "customer_id" int NOT NULL,
                                      "delivary_date" date NOT NULL,
                                      PRIMARY KEY ("id", "delivary_date")
) PARTITION BY RANGE (delivary_date);

CREATE TABLE otus.order_2023 PARTITION OF otus.order_archive FOR VALUES FROM ('2023-01-01') TO ('2024-01-01') TABLESPACE hddOrder;
CREATE TABLE otus.order_2022 PARTITION OF otus.order_archive FOR VALUES FROM ('2022-01-01') TO ('2023-01-01') TABLESPACE hddOrder;
CREATE TABLE otus.order_2021 PARTITION OF otus.order_archive FOR VALUES FROM ('2021-01-01') TO ('2022-01-01') TABLESPACE hddOrder;
CREATE TABLE otus.order_2020 PARTITION OF otus.order_archive FOR VALUES FROM ('2020-01-01') TO ('2021-01-01') TABLESPACE hddOrder;

CREATE TYPE otus.order_item_status AS ENUM ('NEW','DELIVERED','PAID','RETURNED');

CREATE TABLE otus."order_item" (
                                   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   "order_id" bigint NOT NULL,
                                   "product_item_id" bigint NOT NULL,
                                   "delivery_kind_id" int NOT NULL,
                                   "supplier_pick_up_point_id" int NOT NULL,
                                   "amount" decimal(10,2) NOT NULL,
                                   "total_cost" decimal(19,4) NOT NULL,
                                   "delivery_date" date NOT NULL,
                                   "status" otus.order_item_status NOT NULL,
                                   PRIMARY KEY ("id", "delivery_date")
) PARTITION BY RANGE (delivery_date);

CREATE TABLE otus.order_item_2024 PARTITION OF otus.order_item FOR VALUES FROM ('2024-01-01') TO ('2025-01-01') TABLESPACE ssdOrder;
CREATE TABLE otus.order_item_2025 PARTITION OF otus.order_item FOR VALUES FROM ('2025-01-01') TO ('2026-01-01') TABLESPACE ssdOrder;
CREATE TABLE otus.order_item_2026 PARTITION OF otus.order_item FOR VALUES FROM ('2026-01-01') TO ('2027-01-01') TABLESPACE ssdOrder;
CREATE TABLE otus.order_item_2027 PARTITION OF otus.order_item FOR VALUES FROM ('2027-01-01') TO ('2028-01-01') TABLESPACE ssdOrder;

CREATE TABLE otus."order_item_archive" (
                                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                           "order_id" bigint NOT NULL,
                                           "product_item_id" bigint NOT NULL,
                                           "delivery_kind_id" int NOT NULL,
                                           "supplier_pick_up_point_id" int NOT NULL,
                                           "amount" decimal(10,2) NOT NULL,
                                           "total_cost" decimal(19,4) NOT NULL,
                                           "delivery_date" date NOT NULL,
                                           "status" otus.order_item_status NOT NULL,
                                           PRIMARY KEY ("id", "delivery_date")
) PARTITION BY RANGE (delivery_date);

CREATE TABLE otus.order_item_2023 PARTITION OF otus.order_item_archive FOR VALUES FROM ('2023-01-01') TO ('2024-01-01') TABLESPACE hddOrder;
CREATE TABLE otus.order_item_2022 PARTITION OF otus.order_item_archive FOR VALUES FROM ('2022-01-01') TO ('2023-01-01') TABLESPACE hddOrder;
CREATE TABLE otus.order_item_2021 PARTITION OF otus.order_item_archive FOR VALUES FROM ('2021-01-01') TO ('2022-01-01') TABLESPACE hddOrder;
CREATE TABLE otus.order_item_2020 PARTITION OF otus.order_item_archive FOR VALUES FROM ('2020-01-01') TO ('2021-01-01') TABLESPACE hddOrder;

CREATE TABLE otus."supplier" (
                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                 "name" varchar(40) NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."unit" (
                             "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                             "name" varchar(30) NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."country" (
                                "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                "name" varchar(20) UNIQUE NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."region" (
                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                               "name" varchar(30) NOT NULL,
                               "country_fk" int NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."city" (
                             "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                             "name" varchar(50) NOT NULL,
                             "country_fk" int NOT NULL,
                             "region_fk" int
) TABLESPACE ssdOrder;

CREATE TABLE otus."street" (
                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                               "name" varchar(100) NOT NULL,
                               "city_fk" int NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."postal_code" (
                                    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                    "name" varchar(30) UNIQUE NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."building_number" (
                                        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                        "number" varchar(10) UNIQUE NOT NULL,
                                        "street_fk" int NOT NULL,
                                        "postal_code_fk" int NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."warehouse_contact_data" (
                                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                               "warehouse_fk" int NOT NULL,
                                               "country_fk" int NOT NULL,
                                               "region_fk" int,
                                               "city_fk" int NOT NULL,
                                               "street_fk" int NOT NULL,
                                               "building_number_fk" int NOT NULL,
                                               "postal_code_fk" int NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."warehouse" (
                                  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                  "active" boolean NOT NULL DEFAULT true,
                                  "supplier_fk" INT NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."customer_contact_data" (
                                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                              "customer_fk" int NOT NULL,
                                              "country_fk" int NOT NULL,
                                              "region_fk" int,
                                              "city_fk" int NOT NULL,
                                              "street_fk" int NOT NULL,
                                              "building_number_fk" int NOT NULL,
                                              "postal_code_fk" int NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."supplier_pick_up_point" (
                                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                               "supplier_fk" int NOT NULL
) TABLESPACE ssdOrder;

CREATE TABLE otus."supplier_pick_up_point_contact_data" (
                                                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                                            "supplier_pick_up_point_fk" int NOT NULL,
                                                            "country_fk" int NOT NULL,
                                                            "region_fk" int,
                                                            "city_fk" int NOT NULL,
                                                            "street_fk" int NOT NULL,
                                                            "building_number_fk" int NOT NULL,
                                                            "postal_code_fk" int NOT NULL
) TABLESPACE ssdOrder;

CREATE TYPE otus.delivery_kind_kind AS ENUM ('INTERNATIONAL', 'INTERCITY', 'ORDINARY');

CREATE TABLE otus."delivery_kind" (
                                      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                      "supplier_fk" int NOT NULL,
                                      "name" otus.delivery_kind_kind NOT NULL,
                                      "cost" decimal(19,4) NOT NULL,
                                      "duration" interval NOT NULL
) TABLESPACE ssdOrder;

CREATE UNIQUE INDEX delivery_kind_supplier_fk_name_idx ON otus.delivery_kind (supplier_fk, name);

CREATE TABLE otus."refund" (
                               "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                               "supplier_fk" int NOT NULL,
                               "customer_fk" int NOT NULL,
                               "order_item_id" int NOT NULL,
                               "delivery_date" date NOT NULL
) TABLESPACE ssdOrder;

CREATE UNIQUE INDEX "email_email_text_idx" ON otus."email" ("email_text");

CREATE INDEX "email_customer_fk_idx" ON otus."email" ("customer_fk");

CREATE UNIQUE INDEX "name" ON otus."manufacturer" ("name");

CREATE UNIQUE INDEX "phone_number" ON otus."phone" ("phone_number");

CREATE INDEX "phone_customer_fk_idx" ON otus."phone" ("customer_fk");

CREATE UNIQUE INDEX "product_name_idx" ON otus."product" ("name");

CREATE UNIQUE INDEX "product_category_name_idx" ON otus."product_category" ("name");

CREATE INDEX "product_item_product_fk_idx" ON otus."product_item" ("product_fk");

CREATE INDEX "oi_order_id_idx" ON otus."order_item" ("order_id");

CREATE INDEX "order_item_delivery_date_idx" ON otus."order_item" ("delivery_date");

CREATE UNIQUE INDEX "supplier_name_idx" ON otus."supplier" ("name");

COMMENT ON COLUMN otus."manufacturer"."name" IS 'Manufacturer name';

COMMENT ON COLUMN otus."product"."name" IS 'Product name';

COMMENT ON COLUMN otus."product"."unit_fk" IS 'Product unit';

COMMENT ON COLUMN otus."product_category"."name" IS 'Product category name';

COMMENT ON COLUMN otus."product_item"."price" IS 'Price';

COMMENT ON COLUMN otus."product_item"."amount" IS 'Available count in warehousefor supplier';

COMMENT ON COLUMN otus."order"."delivary_date" IS 'Date of delivering the whole order';

COMMENT ON COLUMN otus."order_item"."amount" IS 'Count of bought product';

COMMENT ON COLUMN otus."order_item"."total_cost" IS 'Total cost for current price and count';

COMMENT ON COLUMN otus."order_item"."delivery_date" IS 'Date of delivering the order';

COMMENT ON COLUMN otus."unit"."name" IS 'Product unit';

ALTER TABLE otus."email" ADD CONSTRAINT "email_ibfk_1" FOREIGN KEY ("customer_fk") REFERENCES otus."customer" ("id");

ALTER TABLE otus."product" ADD FOREIGN KEY ("unit_fk") REFERENCES otus."unit" ("id");

ALTER TABLE otus."product" ADD FOREIGN KEY ("manufacturer_fk") REFERENCES otus."manufacturer" ("id");

ALTER TABLE otus."product_category_ref" ADD FOREIGN KEY ("product_fk") REFERENCES otus."product" ("id");

ALTER TABLE otus."product_category_ref" ADD FOREIGN KEY ("product_category_fk") REFERENCES otus."product_category" ("id");

ALTER TABLE otus."product_item" ADD FOREIGN KEY ("product_fk") REFERENCES otus."product" ("id");

ALTER TABLE otus."product_item" ADD FOREIGN KEY ("supplier_fk") REFERENCES otus."supplier" ("id");

ALTER TABLE otus."phone" ADD CONSTRAINT "phone._ibfk_1" FOREIGN KEY ("customer_fk") REFERENCES otus."customer" ("id");

ALTER TABLE otus."region" ADD FOREIGN KEY ("country_fk") REFERENCES otus."country" ("id");

ALTER TABLE otus."city" ADD FOREIGN KEY ("country_fk") REFERENCES otus."country" ("id");

ALTER TABLE otus."city" ADD FOREIGN KEY ("region_fk") REFERENCES otus."region" ("id");

ALTER TABLE otus."street" ADD FOREIGN KEY ("city_fk") REFERENCES otus."city" ("id");

ALTER TABLE otus."building_number" ADD FOREIGN KEY ("street_fk") REFERENCES otus."street" ("id");

ALTER TABLE otus."building_number" ADD FOREIGN KEY ("postal_code_fk") REFERENCES otus."postal_code" ("id");

ALTER TABLE otus."warehouse_contact_data" ADD FOREIGN KEY ("warehouse_fk") REFERENCES otus."warehouse" ("id");

ALTER TABLE otus."warehouse_contact_data" ADD FOREIGN KEY ("country_fk") REFERENCES otus."country" ("id");

ALTER TABLE otus."warehouse_contact_data" ADD FOREIGN KEY ("region_fk") REFERENCES otus."region" ("id");

ALTER TABLE otus."warehouse_contact_data" ADD FOREIGN KEY ("city_fk") REFERENCES otus."city" ("id");

ALTER TABLE otus."warehouse_contact_data" ADD FOREIGN KEY ("street_fk") REFERENCES otus."street" ("id");

ALTER TABLE otus."warehouse_contact_data" ADD FOREIGN KEY ("building_number_fk") REFERENCES otus."building_number" ("id");

ALTER TABLE otus."warehouse_contact_data" ADD FOREIGN KEY ("postal_code_fk") REFERENCES otus."postal_code" ("id");

ALTER TABLE otus."product_item" ADD FOREIGN KEY ("warehouse_fk") REFERENCES otus."warehouse" ("id");

ALTER TABLE otus."customer_contact_data" ADD FOREIGN KEY ("customer_fk") REFERENCES otus."customer" ("id");

ALTER TABLE otus."customer_contact_data" ADD FOREIGN KEY ("country_fk") REFERENCES otus."country" ("id");

ALTER TABLE otus."customer_contact_data" ADD FOREIGN KEY ("region_fk") REFERENCES otus."region" ("id");

ALTER TABLE otus."customer_contact_data" ADD FOREIGN KEY ("city_fk") REFERENCES otus."city" ("id");

ALTER TABLE otus."customer_contact_data" ADD FOREIGN KEY ("street_fk") REFERENCES otus."street" ("id");

ALTER TABLE otus."customer_contact_data" ADD FOREIGN KEY ("building_number_fk") REFERENCES otus."building_number" ("id");

ALTER TABLE otus."customer_contact_data" ADD FOREIGN KEY ("postal_code_fk") REFERENCES otus."postal_code" ("id");

ALTER TABLE otus."supplier_pick_up_point" ADD FOREIGN KEY ("supplier_fk") REFERENCES otus."supplier" ("id");

ALTER TABLE otus."supplier_pick_up_point_contact_data" ADD FOREIGN KEY ("supplier_pick_up_point_fk") REFERENCES otus."supplier_pick_up_point" ("id");

ALTER TABLE otus."supplier_pick_up_point_contact_data" ADD FOREIGN KEY ("country_fk") REFERENCES otus."country" ("id");

ALTER TABLE otus."supplier_pick_up_point_contact_data" ADD FOREIGN KEY ("region_fk") REFERENCES otus."region" ("id");

ALTER TABLE otus."supplier_pick_up_point_contact_data" ADD FOREIGN KEY ("city_fk") REFERENCES otus."city" ("id");

ALTER TABLE otus."supplier_pick_up_point_contact_data" ADD FOREIGN KEY ("street_fk") REFERENCES otus."street" ("id");

ALTER TABLE otus."supplier_pick_up_point_contact_data" ADD FOREIGN KEY ("building_number_fk") REFERENCES otus."building_number" ("id");

ALTER TABLE otus."supplier_pick_up_point_contact_data" ADD FOREIGN KEY ("postal_code_fk") REFERENCES otus."postal_code" ("id");

ALTER TABLE otus."delivery_kind" ADD FOREIGN KEY ("supplier_fk") REFERENCES otus."supplier" ("id");

ALTER TABLE otus."refund" ADD FOREIGN KEY ("supplier_fk") REFERENCES otus."supplier" ("id");

ALTER TABLE otus."refund" ADD FOREIGN KEY ("customer_fk") REFERENCES otus."customer" ("id");

ALTER TABLE otus.warehouse ADD FOREIGN KEY ("supplier_fk") REFERENCES otus."supplier" ("id");
