version: '3.1'

services:
  sysbench:
    container_name: hw9_sysbench
    image: perconalab/sysbench
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:8.0.38
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config:/config
    ports:
      - "3000:3000"
      - "3001:3001"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
  otusdb:
    container_name: hw9_otusdb
    restart: always
    image: mysql:8.4.0
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    command:
      --init-file /init.sql
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/init.sql
      - ./custom.conf:/etc/mysql/conf.d
      - ./manufactorer.csv:/var/lib/mysql-files/manufactorer.csv
      - ./some_customers.csv:/var/lib/mysql-files/some_customers.csv
    expose:
      - "3306"
    ports:
      - "3309:3306"

volumes:
  data:
  config: