INSERT INTO otus.unit(name) VALUES ('unit');
INSERT INTO otus.manufacturer(name) VALUES ('Samsung');
INSERT INTO otus.product_category(name) VALUES ('appliances');

INSERT INTO otus.product(name, manufacturer_fk, unit_fk) VALUES
                                                             ('Refrigerator', 1, 1),
                                                             ('Washing machine', 1, 1),
                                                             ('Dishwasher', 1, 1),
                                                             ('Oven', 1, 1),
                                                             ('Microwave', 1, 1),
                                                             ('Coffee maker', 1, 1),
                                                             ('Toaster', 1, 1),
                                                             ('Blender', 1, 1),
                                                             ('Food processor', 1, 1),
                                                             ('Slow cooker', 1, 1),
                                                             ('Air fryer', 1, 1),
                                                             ('Rice cooker', 1, 1),
                                                             ('Stand mixer', 1, 1),
                                                             ('Electric kettle', 1, 1),
                                                             ('Juicer', 1, 1),
                                                             ('Electric griddle', 1, 1),
                                                             ('Waffle maker', 1, 1),
                                                             ('Bread maker', 1, 1),
                                                             ('Ice cream maker', 1, 1),
                                                             ('Pressure cooker', 1, 1),
                                                             ('Deep fryer', 1, 1),
                                                             ('Vacuum cleaner', 1, 1),
                                                             ('Steam mop', 1, 1),
                                                             ('Robot vacuum', 1, 1),
                                                             ('Carpet cleaner', 1, 1),
                                                             ('Air purifier', 1, 1),
                                                             ('Humidifier', 1, 1),
                                                             ('Dehumidifier', 1, 1),
                                                             ('Space heater', 1, 1),
                                                             ('Fan', 1, 1),
                                                             ('Air conditioner', 1, 1),
                                                             ('Portable air conditioner', 1, 1),
                                                             ('Tower fan', 1, 1),
                                                             ('Ceiling fan', 1, 1),
                                                             ('Dehydrator', 1, 1),
                                                             ('Water filter', 1, 1),
                                                             ('Water dispenser', 1, 1),
                                                             ('Water purifier', 1, 1),
                                                             ('Ice maker', 1, 1),
                                                             ('Garbage disposal', 1, 1),
                                                             ('Trash compactor', 1, 1),
                                                             ('Range hood', 1, 1),
                                                             ('Food dehydrator', 1, 1),
                                                             ('Electric grill', 1, 1),
                                                             ('Food scale', 1, 1),
                                                             ('Electric can opener', 1, 1),
                                                             ('Espresso machine', 1, 1),
                                                             ('Tea kettle', 1, 1),
                                                             ('Wine cooler', 1, 1),
                                                             ('Blender', 1, 1),
                                                             ('Food processor', 1, 1),
                                                             ('Slow cooker', 1, 1),
                                                             ('Rice cooker', 1, 1),
                                                             ('Stand mixer', 1, 1),
                                                             ('Hand mixer', 1, 1),
                                                             ('Mixer', 1, 1),
                                                             ('Toaster', 1, 1),
                                                             ('Toaster oven', 1, 1),
                                                             ('Coffee maker', 1, 1),
                                                             ('Espresso maker', 1, 1),
                                                             ('Electric kettle', 1, 1),
                                                             ('Ice cream maker', 1, 1),
                                                             ('Juicer', 1, 1),
                                                             ('Waffle maker', 1, 1),
                                                             ('Crepe maker', 1, 1),
                                                             ('Pancake maker', 1, 1),
                                                             ('Hot plate', 1, 1),
                                                             ('Deep fryer', 1, 1),
                                                             ('Air fryer', 1, 1),
                                                             ('Quesadilla maker', 1, 1),
                                                             ('Ice maker', 1, 1),
                                                             ('Water cooler', 1, 1),
                                                             ('Crockpot', 1, 1),
                                                             ('Bread maker', 1, 1),
                                                             ('Popcorn maker', 1, 1),
                                                             ('Nutribullet', 1, 1),
                                                             ('Food steamer', 1, 1),
                                                             ('Food saver', 1, 1),
                                                             ('Vacuum sealer', 1, 1),
                                                             ('Food dehydrator', 1, 1),
                                                             ('Yogurt maker', 1, 1),
                                                             ('Sous vide machine', 1, 1),
                                                             ('Electric skillet', 1, 1),
                                                             ('Fondue pot', 1, 1),
                                                             ('Rice maker', 1, 1),
                                                             ('Pressure cooker', 1, 1),
                                                             ('Slow cooker', 1, 1),
                                                             ('Indoor grill', 1, 1),
                                                             ('Panini press', 1, 1),
                                                             ('Food chopper', 1, 1),
                                                             ('Food slicer', 1, 1),
                                                             ('Mandoline', 1, 1),
                                                             ('Food scale', 1, 1),
                                                             ('Meat thermometer', 1, 1),
                                                             ('Bread machine', 1, 1),
                                                             ('Ice cream maker', 1, 1),
                                                             ('Frozen yogurt maker', 1, 1),
                                                             ('Popcorn machine', 1, 1),
                                                             ('Cotton candy machine', 1, 1),
                                                             ('Slushie machine', 1, 1) ON CONFLICT (name) DO NOTHING;


INSERT INTO otus.product_category_ref(product_category_fk, product_fk)
SELECT 1, product.id FROM otus.product;

INSERT INTO otus.supplier(name) VALUES ('entrepreneur');

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-14', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-13', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-12', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-11', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-10', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-09', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-08', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-07', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-07', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-06', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-05', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-04', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.product_item(supplier_fk, product_fk, delivery_date, price, amount)
SELECT 1, product.id, '2024-04-03', (random() * 1000)::numeric(10, 0), (random() * 100)::numeric(10, 0) FROM otus.product;

INSERT INTO otus.customer(first_name, last_name)
select distinct
    ('[0:199]={"John",
"Mary",
"James",
"Susan",
"Robert",
"Linda",
"William",
"Karen",
"Michael",
"Patricia",
"David",
"Jennifer",
"Richard",
"Deborah",
"Joseph",
"Barbara",
"Charles",
"Elizabeth",
"Thomas",
"Lisa",
"Daniel",
"Nancy",
"Matthew",
"Michelle",
"Donald",
"Sandra",
"Mark",
"Kimberly",
"Christopher",
"Donna",
"George",
"Carol",
"Kenneth",
"Amanda",
"Steven",
"Pamela",
"Edward",
"Laura",
"Brian",
"Stephanie",
"Ronald",
"Christine",
"Anthony",
"Cynthia",
"Paul",
"Melissa",
"Kevin",
"Sharon",
"Jason",
"Angela",
"Scott",
"Tammy",
"Eric",
"Tracy",
"Gregory",
"Julie",
"Jeffrey",
"Janet",
"Timothy",
"Brenda",
"Andrew",
"Deborah",
"Jeffrey",
"Ruth",
"Dennis",
"Betty",
"Gregory",
"Joyce",
"Joshua",
"Diane",
"William",
"Helen",
"Brian",
"Marie",
"Ronald",
"Beverly",
"Daniel",
"Theresa",
"Joseph",
"Cheryl",
"Larry",
"Marilyn",
"Frank",
"Joann",
"Samuel",
"Kathleen",
"Raymond",
"Ann",
"Patrick",
"Virginia",
"Charles",
"Marilyn",
"Robert",
"Alice",
"Stephen",
"Jacqueline",
"Gary",
"Frances",
"Douglas",
"Kathryn",
"Peter",
"Margaret",
"Richard",
"Irene",
"Anthony",
"Rachel",
"William",
"Louise",
"Kevin",
"Martha",
"Thomas",
"Sharon",
"Jason",
"Judith",
"Christopher",
"Beverly",
"Kenneth",
"Carolyn",
"Gregory",
"Paula",
"Timothy",
"Susan",
"Edward",
"Dorothy",
"Daniel",
"Sarah",
"Andrew",
"Pamela",
"William",
"Gail",
"Michael",
"Nancy",
"Charles",
"Amy",
"Robert",
"Jessica",
"John",
"Victoria",
"Steven",
"Donna",
"Joseph",
"Lori",
"David",
"Christina",
"James",
"Laura",
"George",
"Theresa",
"Brian",
"Elizabeth",
"Christopher",
"Karen",
"Kenneth",
"Lisa",
"Timothy",
"Michelle",
"Richard",
"Tammy",
"Jason",
"Angela",
"Daniel",
"Cynthia",
"Matthew",
"Lisa",
"Robert",
"Kimberly",
"Thomas",
"Jennifer",
"Donald",
"Deborah",
"William",
"Susan",
"Mark",
"Nancy",
"Anthony",
"Patricia",
"Scott",
"Sharon",
"Paul",
"Pamela",
"Ronald",
"Cynthia",
"Jeffrey",
"Donna",
"Dennis",
"Brenda",
"Gregory",
"Julie",
"Edward",
"Laura",
"Brian",
"Christine",
"Samuel",
"Karen",
"Eric",
"Margaret",
"Joshua",
"Martha",
"Frank",
"Helen"}'::text[])
        [floor(random()*200)] first_name,
    ('[0:995]={"Abbott",
"Acevedo",
"Acosta",
"Adams",
"Adkins",
"Aguilar",
"Aguirre",
"Albert",
"Alexander",
"Ali",
"Allen",
"Allison",
"Alvarado",
"Alvarez",
"Andersen",
"Anderson",
"Andrade",
"Andrews",
"Anthony",
"Archer",
"Arias",
"Armstrong",
"Arnold",
"Arroyo",
"Ashley",
"Atkins",
"Atkinson",
"Austin",
"Avery",
"Avila",
"Ayala",
"Ayers",
"Bailey",
"Baird",
"Baker",
"Baldwin",
"Ball",
"Ballard",
"Baltimore",
"Banks",
"Barber",
"Barker",
"Barnes",
"Barnett",
"Barr",
"Barrera",
"Barrett",
"Barron",
"Barry",
"Bartlett",
"Barton",
"Bass",
"Bates",
"Bauer",
"Bautista",
"Baxter",
"Bean",
"Beard",
"Beasley",
"Beck",
"Becker",
"Bell",
"Bender",
"Benjamin",
"Bennett",
"Benson",
"Bentley",
"Benton",
"Berg",
"Berger",
"Bernard",
"Berry",
"Best",
"Biffle",
"Bird",
"Bishop",
"Black",
"Blackburn",
"Blackwell",
"Blair",
"Blake",
"Blanchard",
"Blankenship",
"Blevins",
"Bolton",
"Bond",
"Bonner",
"Booker",
"Boone",
"Booth",
"Bowen",
"Bowers",
"Bowman",
"Boyd",
"Boyer",
"Boyle",
"Bradford",
"Bradley",
"Bradshaw",
"Brady",
"Branch",
"Brandt",
"Braun",
"Bray",
"Brennan",
"Brewer",
"Bridges",
"Briggs",
"Bright",
"Brock",
"Brooks",
"Brown",
"Browning",
"Bruce",
"Bryan",
"Bryant",
"Buchanan",
"Buck",
"Buckley",
"Bullock",
"Burch",
"Burgess",
"Burke",
"Burnett",
"Burns",
"Burton",
"Bush",
"Butler",
"Byers",
"Byrd",
"Cabrera",
"Cain",
"Calderon",
"Caldwell",
"Calhoun",
"Callahan",
"Camacho",
"Cameron",
"Campbell",
"Campos",
"Canine",
"Cannon",
"Cantrell",
"Cantu",
"Cardenas",
"Carey",
"Carlson",
"Carney",
"Carpenter",
"Carr",
"Carrillo",
"Carroll",
"Carson",
"Carter",
"Carver",
"Case",
"Casey",
"Castaneda",
"Castillo",
"Castro",
"Cervantes",
"Chambers",
"Chan",
"Chandler",
"Chaney",
"Chang",
"Chapman",
"Charles",
"Chase",
"Chavez",
"Chen",
"Cheng",
"Cherry",
"Chia",
"Choi",
"Christensen",
"Christian",
"Christianson",
"Chung",
"Church",
"Clark",
"Clarke",
"Clay",
"Clayton",
"Clements",
"Cline",
"Cobb",
"Cochran",
"Coffey",
"Cohen",
"Cole",
"Coleman",
"Collier",
"Collins",
"Colon",
"Combs",
"Compton",
"Conley",
"Conner",
"Conrad",
"Contreras",
"Conway",
"Cook",
"Cooke",
"Cooley",
"Cooper",
"Copeland",
"Cordova",
"Cortez",
"Costa",
"Costello",
"Courtland",
"Cowan",
"Cox",
"Craig",
"Crane",
"Crawford",
"Crosby",
"Cross",
"Crowley",
"Crownover",
"Cruz",
"Cummings",
"Cunningham",
"Curry",
"Curtis",
"Dalton",
"Daly",
"Daniel",
"Daniels",
"Daughenbaugh",
"Daugherty",
"Davenport",
"David",
"Davidson",
"Davies",
"Davis",
"Dawson",
"Day",
"Dean",
"Decker",
"Delaney",
"Deleon",
"Delgado",
"Dennis",
"Diaz",
"Dickerson",
"Dickson",
"Dillon",
"Dimick",
"Dixon",
"Dodson",
"Dollar",
"Dominguez",
"Donahue",
"Donaldson",
"Donnelly",
"Donovan",
"Dorsey",
"Dougherty",
"Douglas",
"Downs",
"Doyle",
"Drake",
"Dudley",
"Duffy",
"Duke",
"Duncan",
"Dunlap",
"Dunn",
"Duran",
"Durham",
"Dyer",
"Easterlin",
"Eaton",
"Edwards",
"Elliott",
"Ellis",
"Ellison",
"English",
"Erickson",
"Escobar",
"Espinoza",
"Estes",
"Estrada",
"Evans",
"Everett",
"Ewing",
"Farley",
"Farmer",
"Farrell",
"Faulkner",
"Felch",
"Ferguson",
"Fernandez",
"Ferrell",
"Fields",
"Figueroa",
"Finley",
"Fischer",
"Fisher",
"FitzGerald",
"FitzPatrick",
"Fleming",
"Fletcher",
"Flores",
"Flowers",
"Floyd",
"Flynn",
"Foley",
"Forbes",
"Ford",
"Foster",
"Fowler",
"Fox",
"Francis",
"Franco",
"Frank",
"Franklin",
"Frazier",
"Frederick",
"Freeman",
"French",
"Frey",
"Friedman",
"Fritz",
"Frost",
"Fry",
"Frye",
"Fuentes",
"Fuller",
"Gaines",
"Gallagher",
"Gallegos",
"Galloway",
"Galvan",
"Gamble",
"Garcia",
"Gardner",
"Garner",
"Garrett",
"Garrison",
"Garza",
"Gates",
"Gentry",
"George",
"Gibbs",
"Gibson",
"Gilbert",
"Giles",
"Gill",
"Gillespie",
"Gilmore",
"Glass",
"Glenn",
"Glover",
"Goldberg",
"Golden",
"Goldstein",
"Goleman",
"Gomez",
"Gonzales",
"Gonzalez",
"Good",
"Goodman",
"Goodwin",
"Gordon",
"Gorman",
"Gould",
"Governor",
"Graham",
"Grant",
"Graves",
"Gray",
"Green",
"Greene",
"Greer",
"Gregory",
"Griffin",
"Griffith",
"Grimes",
"Gross",
"Guerra",
"Guerrero",
"Guthrie",
"Gutierrez",
"Guzman",
"Haas",
"Hahn",
"Hale",
"Haley",
"Hall",
"Hamilton",
"Hammond",
"Hampton",
"Hancock",
"Haney",
"Hanna",
"Hansen",
"Hanson",
"Hardin",
"Harding",
"Hardy",
"Harjo",
"Harkleroad",
"Harkrader",
"Harmon",
"Harper",
"Harrell",
"Harrington",
"Harris",
"Harrison",
"Hart",
"Hartman",
"Harvey",
"Hatfield",
"Hawkins",
"Hayden",
"Hayes",
"Haynes",
"Hays",
"Heath",
"Hebert",
"Henderson",
"Hendricks",
"Hendrix",
"Henry",
"Hensley",
"Henson",
"Herman",
"Hernandez",
"Herrera",
"Herring",
"Hess",
"Hester",
"Hickman",
"Hicks",
"Higgins",
"Hill",
"Hines",
"Hinton",
"Hipple",
"Ho",
"Hobbs",
"Hodge",
"Hodges",
"Hoffman",
"Hogan",
"Holden",
"Holder",
"Holland",
"Holloway",
"Holmes",
"Holt",
"Hood",
"Hooper",
"Hoover",
"Hopkins",
"Horn",
"Horne",
"Horton",
"House",
"Houston",
"Howard",
"Howe",
"Howell",
"Huang",
"Hubbard",
"Huber",
"Hudson",
"Huff",
"Huffman",
"Hughes",
"Hull",
"Humphrey",
"Hunt",
"Hunter",
"Hurley",
"Hurst",
"Hutchinson",
"Huynh",
"Ibarra",
"Imler",
"Ingram",
"Irwin",
"Jackson",
"Jacobs",
"Jacobson",
"James",
"Jarvis",
"Jefferson",
"Jenkins",
"Jennings",
"Jensen",
"Jimenez",
"John",
"Johns",
"Johnson",
"Johnston",
"Jones",
"Jordan",
"Joseph",
"Joyce",
"Juarez",
"Kaiser",
"Kane",
"Kaplan",
"Katz",
"Kaufman",
"Keith",
"Keller",
"Kelley",
"Kelly",
"Kemp",
"Kennedy",
"Kent",
"Kerr",
"Key",
"Khan",
"Kim",
"Kinderman",
"King",
"Kirby",
"Kirk",
"Kitelinger",
"Klein",
"Kline",
"Klish",
"Knapp",
"Knight",
"Knox",
"Koch",
"Kramer",
"Krause",
"Krueger",
"Kuhn",
"Lake",
"Lakin",
"Lam",
"Lamb",
"Lambert",
"Lancaster",
"Landry",
"Lane",
"Lang",
"Lara",
"Larsen",
"Larson",
"Lawrence",
"Lawson",
"Le",
"Leach",
"Leblanc",
"Lee",
"Lehman",
"Leon",
"Leonard",
"Lepley",
"Lester",
"Levine",
"Levy",
"Lewis",
"Li",
"Lim",
"Lin",
"Lindsay",
"Lindsey",
"Little",
"Liu",
"Livingston",
"Lloyd",
"Logan",
"Long",
"Lopez",
"Love",
"Lowe",
"Lowery",
"Lozano",
"Lucas",
"Luna",
"Lynch",
"Lynn",
"Lyons",
"MacDonald",
"Macias",
"Mack",
"Madden",
"Maddox",
"Mahoney",
"Maldonado",
"Malich",
"Malone",
"Maloney",
"Mann",
"Manning",
"Marks",
"Marquez",
"Marsh",
"Marshall",
"Martin",
"Martinez",
"Mason",
"Massey",
"Mathews",
"Mathis",
"Matthews",
"Maxwell",
"May",
"Mayer",
"Maynard",
"Mayo",
"Mays",
"McBride",
"McCall",
"McCann",
"McCarthy",
"McCarty",
"McClain",
"McClure",
"McConnell",
"McCormick",
"McCoy",
"McCullough",
"McDaniel",
"McDonald",
"McDowell",
"McFarland",
"McGee",
"McGowan",
"McGrath",
"McGuire",
"McIntosh",
"McIntyre",
"McKay",
"McKee",
"McKenzie",
"McKinney",
"McKnight",
"McLaughlin",
"McLean",
"McMahon",
"McMillan",
"McNeil",
"McPherson",
"Meadows",
"Medina",
"Mejia",
"Melendez",
"Melton",
"Mendez",
"Mendoza",
"Mercado",
"Mercer",
"Merrill",
"Merritt",
"Meyer",
"Meyers",
"Michael",
"Middleton",
"Miles",
"Miller",
"Mills",
"Miranda",
"Mitchell",
"Molina",
"Monroe",
"Montgomery",
"Montoya",
"Moody",
"Moon",
"Mooney",
"Moore",
"Mora",
"Morales",
"Moran",
"Moreno",
"Morgan",
"Morris",
"Morrison",
"Morrow",
"Morse",
"Morton",
"Moses",
"Mosley",
"Moss",
"Moyer",
"Mueller",
"Mullen",
"Mullins",
"Munoz",
"Murphy",
"Murray",
"Myers",
"Nash",
"Navarro",
"Neal",
"Nelson",
"Newman",
"Newton",
"Nguyen",
"Nichols",
"Nicholson",
"Nielsen",
"Nixon",
"Noble",
"Nolan",
"Norman",
"Norris",
"Norton",
"Novak",
"Nunez",
"Obrien",
"Ochoa",
"Oconnor",
"Oliver",
"Olsen",
"Olson",
"Oneal",
"Oneill",
"Orozco",
"Orr",
"Ortega",
"Ortiz",
"Osborne",
"Owen",
"Owens",
"Pace",
"Pacheco",
"Padilla",
"Page",
"Palmer",
"Park",
"Parker",
"Parks",
"Parrish",
"Parsons",
"Patel",
"Patrick",
"Patterson",
"Patton",
"Paul",
"Payne",
"Pearce",
"Pearson",
"Peck",
"Pena",
"Pennington",
"Perez",
"Perkins",
"Perry",
"Pershing",
"Peters",
"Petersen",
"Peterson",
"Petty",
"Pham",
"Phelps",
"Phillips",
"Pierce",
"Pineda",
"Pittman",
"Pitts",
"Pollard",
"Poole",
"Pope",
"Porter",
"Potter",
"Potts",
"Powell",
"Powers",
"Pratt",
"Preston",
"Price",
"Prince",
"Proctor",
"Pruitt",
"Pugh",
"Quinn",
"Ramirez",
"Ramos",
"Ramsey",
"Randall",
"Randolph",
"Rangel",
"Rasmussen",
"Ray",
"Raymond",
"Reed",
"Reese",
"Reeves",
"Reid",
"Reilly",
"Reyes",
"Reynolds",
"Rhodes",
"Rice",
"Rich",
"Richard",
"Richards",
"Richardson",
"Richmond",
"Riddle",
"Ridlehoover",
"Riggs",
"Riley",
"Rios",
"Ritter",
"Rivas",
"Rivera",
"Rivers",
"Roach",
"Robbins",
"Roberson",
"Roberts",
"Robertson",
"Robinson",
"Robles",
"Rocha",
"Rodeheaver",
"Rodenbaugh",
"Rodgers",
"Rodriguez",
"Rogers",
"Rojas",
"Rollins",
"Roman",
"Romero",
"Rosales",
"Rose",
"Ross",
"Roth",
"Rowe",
"Rowland",
"Roy",
"Rubio",
"Ruiz",
"Rush",
"Russell",
"Russo",
"Ryan",
"Salas",
"Salazar",
"Salinas",
"Sampson",
"Sanchez",
"Sanders",
"Sandoval",
"Sanford",
"Santana",
"Santiago",
"Santos",
"Sauerbrey",
"Saunders",
"Savage",
"Sawyer",
"Schaefer",
"Schmidt",
"Schmitt",
"Schneider",
"Schroeder",
"Schultz",
"Schwartz",
"Scott",
"Sellers",
"Serrano",
"Settlemire",
"Sexton",
"Shaffer",
"Shah",
"Shannon",
"Sharp",
"Shaw",
"Shea",
"Shelton",
"Shepard",
"Shepherd",
"Sheppard",
"Sherman",
"Shields",
"Short",
"Silva",
"Simmons",
"Simon",
"Simpson",
"Sims",
"Singh",
"Singleton",
"Skinner",
"Sloan",
"Small",
"Smith",
"Snider",
"Snow",
"Snyder",
"Solis",
"Solomon",
"Sosa",
"Soto",
"Sparks",
"Spears",
"Spence",
"Spencer",
"Stafford",
"Stanley",
"Stanton",
"Stark",
"Steele",
"Stein",
"Stephens",
"Stephenson",
"Stevens",
"Stevenson",
"Stewart",
"Stokes",
"Stone",
"Stout",
"Strickland",
"Strome",
"Strong",
"Stuart",
"Suarez",
"Sullivan",
"Summers",
"Sutton",
"Swanson",
"Sweeney",
"Tanner",
"Tate",
"Taylor",
"Terrell",
"Terry",
"Thobe",
"Thomas",
"Thompson",
"Thornton",
"Todd",
"Torres",
"Townsend",
"Tran",
"Travis",
"Trevino",
"Trujillo",
"Tucker",
"Turner",
"Tyler",
"Underwood",
"Valdez",
"Valencia",
"Valentine",
"Valenzuela",
"Van Every",
"Vance",
"Vargas",
"Vasquez",
"Vaughan",
"Vaughn",
"Vazquez",
"Vega",
"Velasquez",
"Velez",
"Villanueva",
"Villarreal",
"Vincent",
"Vogel",
"Wade",
"Wagner",
"Walker",
"Wall",
"Wallace",
"Waller",
"Walls",
"Walsh",
"Walter",
"Walters",
"Walton",
"Wang",
"Ward",
"Ware",
"Warner",
"Warren",
"Washington",
"Waters",
"Watkins",
"Watson",
"Watts",
"Weaver",
"Webb",
"Weber",
"Webster",
"Weeks",
"Weiss",
"Welch",
"Wells",
"Werner",
"West",
"Wheeler"}'::text[])
        [floor(random()*996)] last_name
from
    generate_series(1, 10 * 10 * 50 * 100);

INSERT INTO otus.purchase(customer_fk, delivary_date)
SELECT id, '2024-04-14' FROM otus.customer;

INSERT INTO otus.purchase_item(purchase_fk, product_item_fk, amount, total_cost, delivery_date)
SELECT id,  (random() * 1040)::integer, (random() * 1000)::numeric(10, 0),(random() * 10000)::numeric(10, 0), '2024-04-13'  FROM otus.purchase;


